config/routes.rb
Vidstock::Application.routes.draw do
  devise_for :users
  get "pages/index"

  # get 'tags/:tag', to: 'videos#index', as: :tag

  resources :videos do
    resources :comments
  end
  resources :user_videos
  root to: 'pages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :video, inverse_of: :comments
  belongs_to :user, inverse_of: :comments
  validates_presence_of :content
  validates_numericality_of :video_id, only_integer: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, inverse_of: :user, dependent: :destroy
  has_many :videos, inverse_of: :user, dependent: :destroy
  validates_presence_of :username

  def admin?
    role == 'admin'
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user, inverse_of: :videos
  has_many :comments, inverse_of: :video, dependent: :destroy

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :video_link
  validates_numericality_of :user_id, only_integer: :true
  validates :downloads, :numericality => { :greater_than_or_equal_to => 0 }
  validates_numericality_of :downloads, only_integer: :true


  def vimeo_id
    regex = /(?:videos|video|\.com)\/([\d]+)/
    unless video_link == ""
      video_link.match(regex)[1]
    end
  end

  def vimeo_url
    "http://www.vimeo.com/#{vimeo_id}"
  end

  def set_thumbnail!
    self.thumbnail = Vimeo::Simple::Video.info(vimeo_id)[0]["thumbnail_large"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @video = Video.find(params[:video_id])
    @comment = Comment.new(comment_params)
    @comment.video = @video
    @comment.user = current_user
    if @comment.save
      redirect_to :back
    else
      redirect_to video_path(@video)
      flash[:error] = "Error! Comment not saved."
    end
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :video_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #landing page / root page / static pages
  def index
    if params[:search] && params[:search][:title]
      title = params[:search][:title]
      @videos = Video.where("title ilike ?", "%#{title}%")
    else
      @videos = Video.all
    end
  end
end

app/controllers/user_videos_controller.rb
class UserVideosController < ApplicationController

  def index
    @videos = current_user.videos
    @videos = @videos.page(params[:page]).per_page(5)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_user!, except: [:show]
  before_filter :authenticate_owner, only: [:edit, :destroy, :update]

  def index
    if params[:search]
      query = params[:search][:query]
      @videos = Video.includes(taggings: [:tag])
        .where("tags.name ilike ? OR title ilike ?",
          "%#{query}%", "%#{query}%")
        .references(:tags)
    else
      @videos = Video.all
    end
    @videos = @videos.page(params[:page]).per_page(5)
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      flash[:notice] = 'Video was updated successfully!'
      redirect_to video_path(@video)
    else
      flash[:error] = 'Error! Could not update video!'
      render :new
    end
  end

  def destroy
    video = Video.find(params[:id])
    video.destroy
    respond_to do |format|
      format.html { redirect_to user_videos_path }
    end
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    @video.set_thumbnail!

    if @video.save
      flash[:notice] = 'Video was successfully uploaded!'
      redirect_to video_path(@video)
    else
      flash[:error] = 'Error! Could not upload video!'
      render :new
    end
  end

  def show
    @video = Video.find(params[:id])
    @comment = Comment.new
    @comments = @video.comments
  end

  private

  def authenticate_owner
    unless Video.find(params[:id]).user == current_user
      redirect_to videos_path, notice: "Unable to authenticate!"
    end
  end

  def video_params
    params.require(:video).permit(:title, :description, :downloads, :user_id, :tag_list, :video_link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def tag_links_for(video)
    links = video.tags[0, 5].map do |t|
      link_to t.name, videos_path(search: { query: t.name })
    end

    if video.tags.count > 5
      (links.join(', ') + "...").html_safe
    else
      (links.join(', ')).html_safe
    end
  end
end

app/views/layouts/_flash_notice.html.erb
<% flash.each do |name, msg| -%>
  <div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, class: name %>
  </div>
<% end -%>

app/views/layouts/_footer.html.erb
<section id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <p>&copy Copyright. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, class: "navbar-brand" do %>
        VIDSTOCK
      <%- end -%>
    </div>
    
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Browse Videos', videos_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Upload', new_video_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Me<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit account info', edit_user_registration_path %></li>
                <li><%= link_to 'My uploads', user_videos_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li> 
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <title>Vidstock - Stock Footage Exchange</title>
</head>

<body>
  <%= render 'layouts/navbar' %>
  
  <section id="wrapper" class='clearfix <%= controller_name + '_' + action_name %>'>
    <%= render 'layouts/flash_notice' %>
    <%= yield %>
  </section>

  <%= render 'layouts/footer' %>
</body>

</html>

app/views/pages/index.html.erb
<div id="kont">
  <video autoplay muted loop>
    <source src="https://s3.amazonaws.com/vidstock/Film_Strip_Stock_Video-H264_75+(2).mp4" type="video/mp4">
    <source src="https://s3.amazonaws.com/vidstock/Film_Strip_Stock_Video-H264_75.ogv" type="video/ogg">
  </video>
  <div id="ent">
    <div class="container">
      <div class="row margin-40">
        <div class="col-sm-12 text-center">
          <div class="headertext">VIDSTOCK</div>
          

          <%= render "videos/search_form" %>

          <% unless user_signed_in? %>
            <a class="btn btn-warning btn-lg" href="users/sign_in.html">Login</a>
            <a class="btn btn-info btn-signup btn-lg" href="users/sign_up.html">Sign up</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<section id="services" class="section">
  <div class="container">
    <div class="row text-center">
      
      <!--Section 1-->
      <div class="col-sm-4 service margin-30">
        <a href="#">
          <i class="fa fa-download fa-4x light-gray"></i>
          <h3>Easy Downloads</h3>
          <p>Search for videos by tag or look them up by title. Easy and powerful searches to get exactly what you're looking for. Stock footage hunting has never been so easy.</p>
        </a>
      </div>
      
      <!--Section 2-->
      <div class="col-sm-4 service margin-30">
        <a href="#">
          <i class="fa fa-video-camera fa-4x light-gray"></i>
          <h3>Royalty Free Videos</h3>
          <p>Need that aerial shot of NYC? Can't afford to travel there to take that single shot? We got you covered. All videos are royalty free. Use them for personal projects, education, events, and more.</p>
        </a>

      </div>
      
      <!--Section 3-->
      <div class="col-sm-4 service margin-30">
        <a href="#">
          <i class="fa fa-users fa-4x light-gray"></i>
          <h3>Contribute</h3>
          <p>Our footage library is constantly growing. Upload your footage on Vimeo, then give back to the community by sharing your links here.</p>
        </a>
      </div>
  
    </div>
  </div>
</section>
    
    
<!--Message Section-->
<section id="content3" class="section">
  <div class="container">
    <div class="row margin-40">
      <div class="col-sm-12 text-center">
        <h2 id="quote">"Vidstock allows anyone to get exactly what they want for their own projects. In an age, where everyone is <br>a filmmaker, this is huge."<br> - ScreenThread</h2>
      </div>
    </div>
  </div>  
</section>

<!--Bottom Section-->
<section id="bottom">
  <div class="container">
    <div class="row margin-40">
      <div class="col-sm-10 col-sm-offset-1 text-center">
        <p>Vidstock | Stock Footage Exchange  |  <a href="mailto:support@themearmada.com"><i class="icon-envelope-alt"></i> support@vidstock.com</a></p>
        <hr>
      </div>
    </div>
  </div>
</section>

app/views/user_videos/index.html.erb
<section id="page-title" class="section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3 id="uploads-title">My uploads</h3>
      </div>
    </div>
  </div>
</section>

<div class="col-md-1"></div>
<div class="col-md-10 center browse_videos_page">
  <ul class="video-tiles">
    <% @videos.each do |video| %>
      <li>
        <div class="browse_video_thumb">
        <%= link_to video_path(video) do %>
          <%= image_tag(video.thumbnail, :class => "vid-thumbnail") %>
          </div>
          <div class="browse_video_title">
            <%= link_to "#{video.title}", video, class: "video-link" %>
            <p id="browse_tags">Tags: <%= tag_links_for(video) %></p>
            <div class="form-horizontal">
              <%= link_to 'Edit', edit_video_path(video), class: "btn btn-success btn-med"  %>
              <%= link_to 'Delete', video, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-med delete-btn"  %>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul> 
  <div class="text-center">
    <%= will_paginate @videos, previous_label: h("<"), next_label: h(">") %>
  </div>
</div>
<div class="col-md-1"></div>

app/views/videos/_search_form.html.erb
<%= simple_form_for :search, url: videos_path, method: :get,
  html: {class: "form-inline search-form browse-search clearfix"} do |f| %>
    <div class="search-form-input">
      <%= f.input :query,
        label: false,
        placeholder: "Search videos by title or tags..",
        input_html: { value: (params[:search][:query] if params[:search]) } %>
    </div>

    <div class="search-form-button">
      <%= f.button :submit,
        value: "Search",
        class: "btn btn-success btn-block" %>
    </div>
<% end %>

app/views/videos/_vimeo.html.erb
<div class="vimeo-wrapper">
    <iframe src="//player.vimeo.com/video/<%= video.vimeo_id %>" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

app/views/videos/edit.html.erb
<section id="signup">
  <div class="container">
    <div class="row margin-40">
      <div class="col-sm-6 col-sm-offset-3 text-center upload">
        <h3>Edit Video</h3>
        <%= simple_form_for @video do |f| %>
          <%= f.input :title, label: 'Title' %>
          <%= f.input :description, label: 'Description' %>
          <%= f.input :video_link, label: 'Vimeo link' %>
          <%= f.input :tag_list, label: 'Tags (seperated by commas)' %>
          <div class="form-actions">
            <input class="btn btn-primary btn-lg upload-btn" name="commit" type="submit" value="Update">
          </div>
        <% end %>
      </div><!--End Col 6-->    
    </div><!--End Row-->
  </div><!--End Container-->
</section>

app/views/videos/index.html.erb
<section class="vid-index-search" class="section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3 id="browse-title">Browse Videos</h3>
        <%= render 'videos/search_form' %>
      </div>
    </div>
  </div>
</section>
<div class="col-md-1"></div>
<div class="col-md-10 center browse_videos_page">
  <ul class="video-tiles">
    <% @videos.each do |video| %>
      <li>
        <div class="browse_video_thumb">
        <%= link_to video_path(video) do %>
          <%= image_tag(video.thumbnail, :class => "vid-thumbnail") %>
          </div>
          <div class="browse_video_title">
            <%= link_to "#{video.title}", video, class: "video-link" %>
            <p id="browse_tags">Tags: <%= tag_links_for(video) %></p>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul> 
  <div class="text-center">
    <%= will_paginate @videos, previous_label: h("<"), next_label: h(">") %>
  </div>
</div>
<div class="col-md-1"></div>

app/views/videos/new.html.erb
<section id="signup">
  <div class="container">
    <div class="row margin-40">
      <div class="col-sm-6 col-sm-offset-3 text-center upload">
        <%= simple_form_for @video do |f| %>
          <%= f.input :title, label: 'Title' %>
          <%= f.input :description, label: 'Description' %>
          <%= f.input :video_link, label: 'Vimeo link' %>
          <%= f.input :tag_list, label: 'Tags (seperated by commas)' %>
          <div class="form-actions">
            <input class="btn btn-primary btn-lg upload-btn" name="commit" type="submit" value="Upload">
          </div>
        <% end %>
      </div><!--End Col 6-->    
    </div><!--End Row-->
  </div><!--End Container-->
</section>

app/views/videos/show.html.erb
<div class="container vid-show">
  <div class="row margin-40">
    <%= render 'videos/vimeo', video: @video %>
    <h2 class="video-title"><%= @video.title %></h2>
    <p class="vid-description"><%= @video.description %></p>
    <%= button_to 'Download', @video.vimeo_url, class: "btn btn-danger btn-lg"  %>

    <h2 class="comments-title">
      Comments
    </h2>

    <% @comments.each do |comment| %>
      <div class="comment-row">
        <p class="comments">
          <b class="comment-user"><%= comment.user.username %></b><br>
          <%= comment.content %>
        </p>
     </div>
    <% end %>


    <%= simple_form_for [@video, @comment] do |f| %>
      <div class="comment-input">
        <%= f.input :content, label: false, placeholder: "Got something to say?", class: "comment-input" %>
      </div>
      <div class="form-actions">
        <input class="btn btn-success btn-lg" name="commit" type="submit" value="Submit">
      </div>
    <% end %>

    <div class="back-link-block">
      <%= link_to 'Browse other videos', videos_path, class: "back-link" %>
    </div>
  </div>
</div>